name: Build APK

on:
  push:
    branches:
      - main  # Adjust this to the main branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace 'x' with the desired Python version (e.g., '3.8', '3.9', etc.)

      - name: Install buildozer and dependencies
        run: |
          pip install cython==0.29.23
          pip install buildozer==1.2.0

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              build-essential \
              ccache \
              git \
              libncurses5:i386 \
              libstdc++6:i386 \
              python3 \
              zlib1g:i386 \
              openjdk-11-jdk  # Replace with the appropriate JDK version if needed

      - name: Build APK
        run: |
          buildozer init
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my-app-debug.apk  # Replace with your app's name
          path: ./bin  # The path to the APK after building
